### ISSUE TITLE
Error build with RN 0.47.1

### ISSUE THREAD

**Issue by ntnamag** [ivpusic/react-native-image-crop-picker#404]
### Version
- react-native-image-crop-picker v0.14.4
- react-native v0.47.1
### Platform
- Android
### Debug Log
Build APK error message: 
E:\TuiXachApp\TuiXachEva\node_modules\react-native-image-crop-picker\android\src\main\java\com\reactnative\ivpusic\imagepicker\PickerPackage.java:18: error: method does not override or implement a method from a supertype
    @Override
    ^
Note: E:\TuiXachApp\TuiXachEva\node_modules\react-native-image-crop-picker\android\src\main\java\com\reactnative\ivpusic\imagepicker\PickerModule.java uses or overrides a deprecated API.

**Comment by lampt** [comment]
In react-native v0.47.1, ReactPackage interface does not have "createJSModules" method for override.
So, in react-native-image-crop-picker project library, you must edit like below:

`package com.reactnative.ivpusic.imagepicker;

import com.facebook.react.ReactPackage;
import com.facebook.react.bridge.JavaScriptModule;
import com.facebook.react.bridge.NativeModule;
import com.facebook.react.bridge.ReactApplicationContext;
import com.facebook.react.uimanager.ViewManager;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;

public class PickerPackage implements ReactPackage {

    public PickerPackage() {}    

    @Override
    public List<NativeModule> createNativeModules(
        ReactApplicationContext reactContext) {
        List<NativeModule> modules = new ArrayList<>();
        modules.add(new PickerModule(reactContext));
        return modules;
    }

   //-------> comment this line    //@Override
    public List<Class<? extends JavaScriptModule>> createJSModules() {
        return Collections.emptyList();
    }

    @Override
    public List<ViewManager> createViewManagers(ReactApplicationContext reactContext) {
        return Collections.emptyList();
    }
}`

**Comment by xshadowlegendx** [comment]
@lampt I had this problem early this morning after upgrading to latest react native version, and following the above step fixed my problem.

**Comment by ivpusic** [comment]
check new version https://github.com/ivpusic/react-native-image-crop-picker/releases/tag/v0.15.0
