### ISSUE TITLE
Can't launch the app after react native upgrade

### ISSUE THREAD

**Issue by ansmonjol** [ivpusic/react-native-image-crop-picker#71]
Hello,

After upgrading my react-native version to 0.33 I get this error : 
`error: PickerModule is not abstract and does not override abstract method onActivityResult(Activity,int,int,Intent) in ActivityEventListener`

### Version

- react-native-image-crop-picker v0.6.0
- react-native-cli: 1.0.0
- react-native: 0.33.0

### Actual behaviour

after running `npm install --save react-native@0.33` I can't launch anymore my app

See stacktrace bellow

### Steps to reproduce

1. npm install --save react-native@0.33
2. react-native -run-android

### Stacktrace
```
/Users/alexandre/Developer/BulbThings-App/node_modules/react-native-image-crop-picker/android/src/main/java/com/reactnative/picker/PickerModule.java:46: error: PickerModule is not abstract and does not override abstract method onActivityResult(Activity,int,int,Intent) in ActivityEventListener
public class PickerModule extends ReactContextBaseJavaModule implements ActivityEventListener {
       ^
/Users/alexandre/Developer/BulbThings-App/node_modules/react-native-image-crop-picker/android/src/main/java/com/reactnative/picker/PickerModule.java:299: error: method does not override or implement a method from a supertype
    @Override
    ^
2 errors
:react-native-image-crop-picker:compileReleaseJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-image-crop-picker:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 14.574 secs
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/android-setup.html
```

Any idea ?

**Comment by ivpusic** [comment]
you should upgrade `react-native-image-crop-picker` to latest (currently 0.9.4) version

**Comment by ansmonjol** [comment]
Thank you, it did the job

**Comment by ansmonjol** [comment]
Now it tell me that the package does not exist
```
/Users/alexandre/Developer/BulbThings-App/android/app/src/main/java/com/bulbthings/app/MainApplication.java:15: error: package com.reactnative.picker does not exist
import com.reactnative.picker.PickerPackage;
                             ^
/Users/alexandre/Developer/BulbThings-App/android/app/src/main/java/com/bulbthings/app/MainApplication.java:36: error: cannot find symbol
          new PickerPackage(),
              ^
  symbol: class PickerPackage
2 errors
:app:compileDebugJavaWithJavac FAILED
```
So I tried to remove those lines in the MainApplication.java file to launch the project but logically the imagePicker function is undefined 
<img width="348" alt="screen shot 2016-09-18 at 15 44 49" src="https://cloud.githubusercontent.com/assets/5517077/18616610/dec5538c-7db6-11e6-8c4d-b6b0a8c081c6.png">
Maybe it's a wrong install from my part ?

**Comment by ivpusic** [comment]
check migration guide for this version https://github.com/ivpusic/react-native-image-crop-picker/releases/tag/v0.7.0

**Comment by adrienthiery** [comment]
Hi @ivpusic,

Just upgraded both react-native to 0.33 and react-native-image-crop-picker to 0.9.4 and I have the same error than `ansmonjol`.

```
 PickerModule is not abstract and does not override abstract method onActivityResult(int,int,Intent) in ActivityEventListener
public class PickerModule extends ReactContextBaseJavaModule implements ActivityEventListener {
       ^
/Users/osedea/Projects/Hey Neighburz/hey-neighburz-app/node_modules/react-native-image-crop-picker/android/src/main/java/com/reactnative/ivpusic/imagepicker/PickerModule.java:441: error: method does not override or implement a method from a supertype
    @Override
    ^
/Users/osedea/Projects/Hey Neighburz/hey-neighburz-app/node_modules/react-native-image-crop-picker/android/src/main/java/com/reactnative/ivpusic/imagepicker/PickerModule.java:452: error: method does not override or implement a method from a supertype
    @Override
    ^
3 errors
:react-native-image-crop-picker:compileReleaseJavaWithJavac FAILED
```

I can't seem to figure out why...

Any idea? 😢

**Comment by adrienthiery** [comment]
@ivpusic : It seems I had done something bad during `react-native upgrade`... I redid it and it works!
