### ISSUE TITLE
Cannot compile v0.8.0 for Android

### ISSUE THREAD

**Issue by priezz** [ivpusic/react-native-image-crop-picker#59]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.8.0
- react-native v0.33.0-rc.0

### Actual behaviour

:react-native-image-crop-picker:compileReleaseJavaWithJavac
.../node_modules/react-native-image-crop-picker/android/src/main/java/com/reactnative/ivpusic/imagepicker/PickerModule.java:46: error: PickerModule is not abstract and does not override abstract method onActivityResult(Activity,int,int,Intent) in ActivityEventListener
public class PickerModule extends ReactContextBaseJavaModule implements ActivityEventListener {
       ^
.../node_modules/react-native-image-crop-picker/android/src/main/java/com/reactnative/ivpusic/imagepicker/PickerModule.java:299: error: method does not override or implement a method from a supertype
    @Override
    ^
2 errors
:react-native-image-crop-picker:compileReleaseJavaWithJavac FAILED

### Steps to reproduce
Install accordingly to instructions, then `react-native run-android`

**Comment by ivpusic** [comment]
this change is introduced in https://github.com/facebook/react-native/commit/fbd2e139103e3d520f6dfc009d6200f8b8168e35 commit for RN0.33. As 0.33 final still is not released this is expected behaviour. 

Once 0.33 is released, I will update `onActivityResult` to new signature.

**Comment by priezz** [comment]
Thanks for the link! I have replaced method definition with
```
    public void onActivityResult(final Activity activity, final int requestCode, final int resultCod
```
and now it works fine.

**Comment by texas697** [comment]
@priezz  your solution is cutoff. can you post it again

**Comment by priezz** [comment]
@texas697, I believe it is in place already https://github.com/ivpusic/react-native-image-crop-picker/blob/master/android/src/main/java/com/reactnative/ivpusic/imagepicker/PickerModule.java#L442
