### ISSUE TITLE
Doesn't compile with RN 0.34.1

### ISSUE THREAD

**Issue by morelazers** [ivpusic/react-native-image-crop-picker#104]
### Version
Tell us which versions you are using: 

- react-native-image-crop-picker v0.8.3
- react-native v0.34.1

### Platform
Tell us to which platform this issue is related

- iOS
- Android

### Expected behaviour
Application compiles.

### Actual behaviour
Application does not compile.

### Steps to reproduce

1. Install the above versions

2. Attempt to compile the app

// stacktrace or any other useful debug info

/node_modules/react-native-image-crop-picker/android/src/main/java/com/reactnative/ivpusic/imagepicker/PickerModule.java:48: 
error: PickerModule is not abstract and does not override abstract method onActivityResult(Activity,int,int,Intent) in ActivityEventListener
public class PickerModule extends ReactContextBaseJavaModule implements ActivityEventListener {
       ^
/node_modules/react-native-image-crop-picker/android/src/main/java/com/reactnative/ivpusic/imagepicker/PickerModule.java:433:
error: method does not override or implement a method from a supertype
    @Override
    ^

Personally I fixed this by just adding in the argument and recompiling, haven't tested fully but it seems to work.

**Comment by ivpusic** [comment]
use latest version (v0.9.7)
